/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectofinal;

/**
 *
 * @author Pablo Che
 */
public class Practica_Unidad3 extends javax.swing.JFrame {

    /**
     * Creates new form Practica_Unidad3
     */
    public Practica_Unidad3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pregunta1 = new javax.swing.ButtonGroup();
        pregunta2 = new javax.swing.ButtonGroup();
        pregunta3 = new javax.swing.ButtonGroup();
        pregunta4 = new javax.swing.ButtonGroup();
        pregunta5 = new javax.swing.ButtonGroup();
        pregunta6 = new javax.swing.ButtonGroup();
        pregunta7 = new javax.swing.ButtonGroup();
        pregunta8 = new javax.swing.ButtonGroup();
        pregunta9 = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        jButton3 = new javax.swing.JButton();
        revisar_practica2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        op_falso4 = new javax.swing.JRadioButton();
        op_verdadero7 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        op_verdadero4 = new javax.swing.JRadioButton();
        op_falso5 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        op_verdadero5 = new javax.swing.JRadioButton();
        op_falso6 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        op_verdadero6 = new javax.swing.JRadioButton();
        op_falso7 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        op_falso8 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        op_verdadero8 = new javax.swing.JRadioButton();
        op_falso9 = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        op_verdadero9 = new javax.swing.JRadioButton();
        op_verdadero1 = new javax.swing.JRadioButton();
        op_falso1 = new javax.swing.JRadioButton();
        op_falso2 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        op_verdadero2 = new javax.swing.JRadioButton();
        op_falso3 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        op_verdadero3 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        label1.setFont(new java.awt.Font("Dubai Light", 1, 36)); // NOI18N
        label1.setText("Práctica Unidad 3");

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("Regresar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        revisar_practica2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        revisar_practica2.setText("Revisar");
        revisar_practica2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revisar_practica2ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        pregunta4.add(op_falso4);
        op_falso4.setForeground(new java.awt.Color(0, 0, 0));
        op_falso4.setText("Falso");
        op_falso4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_falso4ActionPerformed(evt);
            }
        });

        pregunta7.add(op_verdadero7);
        op_verdadero7.setForeground(new java.awt.Color(0, 0, 0));
        op_verdadero7.setText("Verdadero");
        op_verdadero7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_verdadero7ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Contesta verdadero o falso, según corresponda:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("4. Un triángulo acutángulo no tiene tres ángulos agudos.");

        pregunta4.add(op_verdadero4);
        op_verdadero4.setForeground(new java.awt.Color(0, 0, 0));
        op_verdadero4.setText("Verdadero");
        op_verdadero4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_verdadero4ActionPerformed(evt);
            }
        });

        pregunta5.add(op_falso5);
        op_falso5.setForeground(new java.awt.Color(0, 0, 0));
        op_falso5.setText("Falso");
        op_falso5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_falso5ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("5. Un triángulo rectángulo tiene un ángulo recto.");

        pregunta5.add(op_verdadero5);
        op_verdadero5.setForeground(new java.awt.Color(0, 0, 0));
        op_verdadero5.setText("Verdadero");
        op_verdadero5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_verdadero5ActionPerformed(evt);
            }
        });

        pregunta6.add(op_falso6);
        op_falso6.setForeground(new java.awt.Color(0, 0, 0));
        op_falso6.setText("Falso");
        op_falso6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_falso6ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("6. Los polígonos regulares son aquellos que tienen todos sus lados y ángulos iguales");

        pregunta6.add(op_verdadero6);
        op_verdadero6.setForeground(new java.awt.Color(0, 0, 0));
        op_verdadero6.setText("Verdadero");
        op_verdadero6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_verdadero6ActionPerformed(evt);
            }
        });

        pregunta7.add(op_falso7);
        op_falso7.setForeground(new java.awt.Color(0, 0, 0));
        op_falso7.setText("Falso");
        op_falso7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_falso7ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("1. En un triángulo existen dos tipos de ángulos");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("7. La suma de todos los ángulos exteriores de cualquier polígono siempre es 300°");

        pregunta8.add(op_falso8);
        op_falso8.setForeground(new java.awt.Color(0, 0, 0));
        op_falso8.setText("Falso");
        op_falso8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_falso8ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("8. Un pentágono tiene 5 diagonales:");

        pregunta8.add(op_verdadero8);
        op_verdadero8.setForeground(new java.awt.Color(0, 0, 0));
        op_verdadero8.setText("Verdadero");
        op_verdadero8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_verdadero8ActionPerformed(evt);
            }
        });

        pregunta9.add(op_falso9);
        op_falso9.setForeground(new java.awt.Color(0, 0, 0));
        op_falso9.setText("Falso");
        op_falso9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_falso9ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("9. Los polígonos regulares todos sus lados miden lo diferente.");

        pregunta9.add(op_verdadero9);
        op_verdadero9.setForeground(new java.awt.Color(0, 0, 0));
        op_verdadero9.setText("Verdadero");
        op_verdadero9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_verdadero9ActionPerformed(evt);
            }
        });

        pregunta1.add(op_verdadero1);
        op_verdadero1.setForeground(new java.awt.Color(0, 0, 0));
        op_verdadero1.setText("Verdadero");
        op_verdadero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_verdadero1ActionPerformed(evt);
            }
        });

        pregunta1.add(op_falso1);
        op_falso1.setForeground(new java.awt.Color(0, 0, 0));
        op_falso1.setText("Falso");
        op_falso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_falso1ActionPerformed(evt);
            }
        });

        pregunta2.add(op_falso2);
        op_falso2.setForeground(new java.awt.Color(0, 0, 0));
        op_falso2.setText("Falso");
        op_falso2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_falso2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("2. El ángulo interior lo forman un lado y su prolongación");

        pregunta2.add(op_verdadero2);
        op_verdadero2.setForeground(new java.awt.Color(0, 0, 0));
        op_verdadero2.setText("Verdadero");
        op_verdadero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_verdadero2ActionPerformed(evt);
            }
        });

        pregunta3.add(op_falso3);
        op_falso3.setForeground(new java.awt.Color(0, 0, 0));
        op_falso3.setText("Falso");
        op_falso3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_falso3ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("3. La suma de los ángulos interiores de un triángulo es igual a 180°.");

        pregunta3.add(op_verdadero3);
        op_verdadero3.setForeground(new java.awt.Color(0, 0, 0));
        op_verdadero3.setText("Verdadero");
        op_verdadero3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_verdadero3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(op_verdadero1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(op_falso1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(op_verdadero2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(op_falso2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(op_verdadero3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(op_falso3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(op_verdadero4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(op_falso4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(op_verdadero5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(op_falso5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(op_verdadero6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(op_falso6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(op_verdadero7, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(op_falso7, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(op_verdadero8, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(op_falso8, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(op_verdadero9, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(op_falso9, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(op_verdadero1)
                    .addComponent(op_falso1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(op_verdadero2)
                    .addComponent(op_falso2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(op_verdadero3)
                    .addComponent(op_falso3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(op_verdadero4)
                    .addComponent(op_falso4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(op_verdadero5)
                    .addComponent(op_falso5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(op_verdadero6)
                    .addComponent(op_falso6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(op_verdadero7)
                    .addComponent(op_falso7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(op_verdadero8)
                    .addComponent(op_falso8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(op_verdadero9)
                    .addComponent(op_falso9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(283, 283, 283))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(296, 296, 296)
                .addComponent(revisar_practica2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(revisar_practica2)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Unidad_3 u1 = new Unidad_3();
        u1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    int calificacion=0;
    private void revisar_practica2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revisar_practica2ActionPerformed

        if(op_verdadero1.isSelected()){

            calificacion=+1;
        }
        if(op_falso2.isSelected()){

            calificacion=calificacion+1;
        }
        if(op_verdadero3.isSelected()){

            calificacion=calificacion+1;
        }
        if(op_falso4.isSelected()){

            calificacion=calificacion+1;
        }
        if(op_verdadero5.isSelected()){

            calificacion=calificacion+1;
        }
        if(op_verdadero6.isSelected()){

            calificacion=calificacion+1;
        }
        if(op_falso7.isSelected()){

            calificacion=calificacion+1;
        }
        if(op_verdadero8.isSelected()){

            calificacion=calificacion+1;
        }
        if(op_falso9.isSelected()){

            calificacion=calificacion+1;
        }

        ResultadoPractica resultadoPractica = new ResultadoPractica();
        ResultadoPractica.result_prac.setText("Puntos obtenidos: "+(Integer.toString(calificacion))+"/9");
        ResultadoPractica.unidad = 3;
        resultadoPractica.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_revisar_practica2ActionPerformed

    private void op_falso4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_falso4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_op_falso4ActionPerformed

    private void op_verdadero7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_verdadero7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_op_verdadero7ActionPerformed

    private void op_verdadero4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_verdadero4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_op_verdadero4ActionPerformed

    private void op_falso5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_falso5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_op_falso5ActionPerformed

    private void op_verdadero5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_verdadero5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_op_verdadero5ActionPerformed

    private void op_falso6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_falso6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_op_falso6ActionPerformed

    private void op_verdadero6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_verdadero6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_op_verdadero6ActionPerformed

    private void op_falso7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_falso7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_op_falso7ActionPerformed

    private void op_falso8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_falso8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_op_falso8ActionPerformed

    private void op_verdadero8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_verdadero8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_op_verdadero8ActionPerformed

    private void op_falso9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_falso9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_op_falso9ActionPerformed

    private void op_verdadero9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_verdadero9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_op_verdadero9ActionPerformed

    private void op_verdadero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_verdadero1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_op_verdadero1ActionPerformed

    private void op_falso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_falso1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_op_falso1ActionPerformed

    private void op_falso2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_falso2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_op_falso2ActionPerformed

    private void op_verdadero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_verdadero2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_op_verdadero2ActionPerformed

    private void op_falso3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_falso3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_op_falso3ActionPerformed

    private void op_verdadero3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_verdadero3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_op_verdadero3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Practica_Unidad3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Practica_Unidad3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Practica_Unidad3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Practica_Unidad3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Practica_Unidad3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private javax.swing.JRadioButton op_falso1;
    private javax.swing.JRadioButton op_falso2;
    private javax.swing.JRadioButton op_falso3;
    private javax.swing.JRadioButton op_falso4;
    private javax.swing.JRadioButton op_falso5;
    private javax.swing.JRadioButton op_falso6;
    private javax.swing.JRadioButton op_falso7;
    private javax.swing.JRadioButton op_falso8;
    private javax.swing.JRadioButton op_falso9;
    private javax.swing.JRadioButton op_verdadero1;
    private javax.swing.JRadioButton op_verdadero2;
    private javax.swing.JRadioButton op_verdadero3;
    private javax.swing.JRadioButton op_verdadero4;
    private javax.swing.JRadioButton op_verdadero5;
    private javax.swing.JRadioButton op_verdadero6;
    private javax.swing.JRadioButton op_verdadero7;
    private javax.swing.JRadioButton op_verdadero8;
    private javax.swing.JRadioButton op_verdadero9;
    private javax.swing.ButtonGroup pregunta1;
    private javax.swing.ButtonGroup pregunta2;
    private javax.swing.ButtonGroup pregunta3;
    private javax.swing.ButtonGroup pregunta4;
    private javax.swing.ButtonGroup pregunta5;
    private javax.swing.ButtonGroup pregunta6;
    private javax.swing.ButtonGroup pregunta7;
    private javax.swing.ButtonGroup pregunta8;
    private javax.swing.ButtonGroup pregunta9;
    private javax.swing.JButton revisar_practica2;
    // End of variables declaration//GEN-END:variables
}
